//ESCOLHER UM DOS TEMAS INFORMADOS
//CRIAR REPOSITÓRIO E DEIXAR PÚBLICO
//TER NO MÍNIMO 2 PÁGINAS HTML (DUPLAS 1 TELA CADA)
//PALETA DE CORES
//TER ACESSIBILIDADE EM LIBRAS
// IMPORTAR FONT DO GOOGLE FONTS
// + 1 PONTO SE CRIAR UM FORMULÁRIO PARA O SEU PROJETO
// PRAZO DE ENTREGA: SEXTA-FEIRA 13 
//FAVICON NA JANELA DE NAGEVAÇÃO